# EDA Application with a Real Data Set - Draft Version 1
## https://www.kaggle.com/c/santander-customer-satisfaction

## Data Set

- Santander Bank is asking to help identify dissatisfied customers in their relationship with hundreds of anonymized features. Please visit the website and read details about it.

- 743 columns (ID, TARGET, and features), 76020 rows: train and test data sets.

- The "TARGET" column is the variable to predict. It equals one for unsatisfied customers and 0 for satisfied customers.

- Data file descriptions:

        train.csv - the training set including the target
        test.csv - the test set without the target
        sample_submission.csv - a sample submission file in the correct format


## Goal

- The task: 
    1. to describe the data set
        - data type for each column 
        - missingness
        - univariate summaries
        - bivariate summaries
            - associations
            - correlations
            - patterns
        - multivariate summaries
        - more
    2. to predict the probability that each customer in the test set is an unsatisfied customer.
    3. to predict if a customer is satisfied or dissatisfied with their banking experience.


## Housekeeping

Know: 
- where you are working
- version check
- shorcuts: https://youtu.be/d0oBRIONOEw

Basic packs to use:
- numpy
- pandas
- seaborn
- matplotlib

In [38]:
# Directory working
%pwd #look at the current work dir. import os
#%cd

'C:\\Users\\newstu\\Desktop\\Data\\kaggle'

### Step 1: Source and load the data

In [39]:
# Import necessary libraries and load the data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler



In [40]:
# Check version
import pandas as pd
pd.__version__

'1.0.1'

In [41]:
#import data from directory
train = pd.read_csv("train.csv", index_col='ID') # the train dataset is now a Pandas DataFrame
test = pd.read_csv("test.csv", index_col='ID') # the train dataset is now a Pandas DataFrame
#train = pd.read_csv("Documents/GitHub/ML/santander-customer-satisfaction/train.csv", index_col='ID') # the train dataset is now a Pandas DataFrame
#test = pd.read_csv("Documents/GitHub/ML/santander-customer-satisfaction/test.csv", index_col='ID') # the train dataset is now a Pandas DataFrame

In [42]:
# Alternative way if data is undet the same folder
train = pd.read_csv("train.csv")                    

### Step 2: Data Wrangling 

In [43]:
# We will use train data set for EDA
# Look the number of rows and columns
train.shape

(76020, 371)

In [44]:
# Data types
train.dtypes

ID                           int64
var3                         int64
var15                        int64
imp_ent_var16_ult1         float64
imp_op_var39_comer_ult1    float64
                            ...   
saldo_medio_var44_hace3    float64
saldo_medio_var44_ult1     float64
saldo_medio_var44_ult3     float64
var38                      float64
TARGET                       int64
Length: 371, dtype: object

In [45]:
# Check out the data types, number of entries and other details
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB


In [46]:
# Check out the first 5 rows of the data set
train.head()

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0   1     2     23                 0.0                      0.0   
1   3     2     34                 0.0                      0.0   
2   4     2     23                 0.0                      0.0   
3   8     2     37                 0.0                    195.0   
4  10     2     39                 0.0                      0.0   

   imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                    195.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  ...  \
0                      0.0                      0.0  ...   
1                      0.0                      0.0  ...   
2                      0.0                      0.0  ...   
3                      0.0                      0.0  ...   
4                      0.0                      0.0  ...   

   saldo_medio_var33_hace2  saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
0                      0.0                      0.0                     0.0   
1                      0.0                      0.0                     0.0   
2                      0.0                      0.0                     0.0   
3                      0.0                      0.0                     0.0   
4                      0.0                      0.0                     0.0   

   saldo_medio_var33_ult3  saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
0                     0.0                      0.0                      0.0   
1                     0.0                      0.0                      0.0   
2                     0.0                      0.0                      0.0   
3                     0.0                      0.0                      0.0   
4                     0.0                      0.0                      0.0   

   saldo_medio_var44_ult1  saldo_medio_var44_ult3          var38  TARGET  
0                     0.0                     0.0   39205.170000       0  
1                     0.0                     0.0   49278.030000       0  
2                     0.0                     0.0   67333.770000       0  
3                     0.0                     0.0   64007.970000       0  
4                     0.0                     0.0  117310.979016       0  

[5 rows x 371 columns]

In [47]:
# Given we couldn't see NaNs from the df.info(), let's do this another way
train.isnull().sum() #.nlargest() #.sum() 

ID                         0
var3                       0
var15                      0
imp_ent_var16_ult1         0
imp_op_var39_comer_ult1    0
                          ..
saldo_medio_var44_hace3    0
saldo_medio_var44_ult1     0
saldo_medio_var44_ult3     0
var38                      0
TARGET                     0
Length: 371, dtype: int64

In [48]:
# Number of columns with all zeros as average
np.sum(train.mean()==0)

34

In [49]:
# Which columns have zeros?
?

In [50]:
# Columns with all zeros
zero_mean = (train.mean()==0).to_frame(name='ZeroMean')

In [51]:
zero_mean = zero_mean.loc[zero_mean.ZeroMean]
print(zero_mean)

                               ZeroMean
ind_var2_0                         True
ind_var2                           True
ind_var27_0                        True
ind_var28_0                        True
ind_var28                          True
ind_var27                          True
ind_var41                          True
ind_var46_0                        True
ind_var46                          True
num_var27_0                        True
num_var28_0                        True
num_var28                          True
num_var27                          True
num_var41                          True
num_var46_0                        True
num_var46                          True
saldo_var28                        True
saldo_var27                        True
saldo_var41                        True
saldo_var46                        True
imp_amort_var18_hace3              True
imp_amort_var34_hace3              True
imp_reemb_var13_hace3              True
imp_reemb_var33_hace3              True


In [52]:
# We can get rid of the columns with all zeros, there is no information to gain from them
# This is dangerous way to do!
remove_features = list(zero_mean.index)
print(remove_features)

['ind_var2_0', 'ind_var2', 'ind_var27_0', 'ind_var28_0', 'ind_var28', 'ind_var27', 'ind_var41', 'ind_var46_0', 'ind_var46', 'num_var27_0', 'num_var28_0', 'num_var28', 'num_var27', 'num_var41', 'num_var46_0', 'num_var46', 'saldo_var28', 'saldo_var27', 'saldo_var41', 'saldo_var46', 'imp_amort_var18_hace3', 'imp_amort_var34_hace3', 'imp_reemb_var13_hace3', 'imp_reemb_var33_hace3', 'imp_trasp_var17_out_hace3', 'imp_trasp_var33_out_hace3', 'num_var2_0_ult1', 'num_var2_ult1', 'num_reemb_var13_hace3', 'num_reemb_var33_hace3', 'num_trasp_var17_out_hace3', 'num_trasp_var33_out_hace3', 'saldo_var2_ult1', 'saldo_medio_var13_medio_hace3']


In [53]:
train = train.drop(remove_features, axis=1)
train.shape

(76020, 337)

Notice the number of columns that decreased from original 371 to 337

In [54]:
# Number of columns with all zeros
np.sum(train.mean()==0)

0

In [55]:
# Uniqueness of values using train.unique for each column
?

In [56]:
# Let's look at classes of the target 
train[['TARGET', 'var3']]

TARGET  var3
0           0     2
1           0     2
2           0     2
3           0     2
4           0     2
...       ...   ...
76015       0     2
76016       0     2
76017       0     2
76018       0     2
76019       0     2

[76020 rows x 2 columns]

In [57]:
# Percent of happy-unhappy customers
train['TARGET'].value_counts() / train.shape[0]

# See this data is a unbalanced data. When modeling, this produces an issue tht needs to be handled. 

0    0.960431
1    0.039569
Name: TARGET, dtype: float64

In [58]:
# Happy customers: TARGET==0 vs Unhappy custormers: TARGET==1
df = pd.DataFrame(train.TARGET.value_counts())
df['Percentage'] = 100*df['TARGET']/train.shape[0]
df

TARGET  Percentage
0   73012   96.043147
1    3008    3.956853

### Discover data related issues, type issues, all issues before running EDA

In [59]:
# Check the range of each feature and target values
train.describe()

ID           var3         var15  imp_ent_var16_ult1  \
count   76020.000000   76020.000000  76020.000000        76020.000000   
mean    75964.050723   -1523.199277     33.212865           86.208265   
std     43781.947379   39033.462364     12.956486         1614.757313   
min         1.000000 -999999.000000      5.000000            0.000000   
25%     38104.750000       2.000000     23.000000            0.000000   
50%     76043.000000       2.000000     28.000000            0.000000   
75%    113748.750000       2.000000     40.000000            0.000000   
max    151838.000000     238.000000    105.000000       210000.000000   

       imp_op_var39_comer_ult1  imp_op_var39_comer_ult3  \
count             76020.000000             76020.000000   
mean                 72.363067               119.529632   
std                 339.315831               546.266294   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max               12888.030000             21024.810000   

       imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
count             76020.000000             76020.000000   
mean                  3.559130                 6.472698   
std                  93.155749               153.737066   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max                8237.820000             11073.570000   

       imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  ...  \
count             76020.000000             76020.000000  ...   
mean                  0.412946                 0.567352  ...   
std                  30.604864                36.513513  ...   
min                   0.000000                 0.000000  ...   
25%                   0.000000                 0.000000  ...   
50%                   0.000000                 0.000000  ...   
75%                   0.000000                 0.000000  ...   
max                6600.000000              6600.000000  ...   

       saldo_medio_var33_hace2  saldo_medio_var33_hace3  \
count             76020.000000             76020.000000   
mean                  7.935824                 1.365146   
std                 455.887218               113.959637   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max               50003.880000             20385.720000   

       saldo_medio_var33_ult1  saldo_medio_var33_ult3  \
count            76020.000000            76020.000000   
mean                12.215580                8.784074   
std                783.207399              538.439211   
min                  0.000000                0.000000   
25%                  0.000000                0.000000   
50%                  0.000000                0.000000   
75%                  0.000000                0.000000   
max             138831.630000            91778.730000   

       saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
count             76020.000000             76020.000000   
mean                 31.505324                 1.858575   
std                2013.125393               147.786584   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max              438329.220000             24650.010000   

       saldo_medio_var44_ult1  saldo_medio_var44_ult3         var38  \
count            76020.000000            76020.000000  7.602000e+04   

### Write a code to get all the ranges of the data set

In [60]:
ab = []

for i in train.columns:
    ab.append([i, train[i].min(),train[i].max(), train[i].max()-train[i].min()])

#print(ab) #see this is not good way to print!


#? Research: Effect of Kurtosis and Skewness on Scaling Method (Feature Engineering)
#? Shape of Distri
#? Use of Skewness in Modeling. Next Topic.

In [63]:
ab = []

for i in train.columns:
    ab.append([i, train[i].min(),train[i].max(), train[i].max()-train[i].min(),len(train[train[i] == 0])])

#print(ab) #see this is not good way to print!
df = pd.DataFrame(ab)
df.head()


0         1          2           3      4
0                       ID       1.0  151838.00   151837.00      0
1                     var3 -999999.0     238.00  1000237.00     75
2                    var15       5.0     105.00      100.00      0
3       imp_ent_var16_ult1       0.0  210000.00   210000.00  72301
4  imp_op_var39_comer_ult1       0.0   12888.03    12888.03  66075

In [62]:
# Give column names and make data frame of pandas, then print
cols = ['cols','min','max', 'range'] #add more statistic
df_ranges = pd.DataFrame(ab,columns=cols)
df_ranges

ValueError: 4 columns passed, passed data had 5 columns

In [ ]:
# When scaling, high values will skew the transformation. So use percentile or robust scaling method
# How to handle these high values or coded values in a variable? -999999
?

In [ ]:
df_ranges.sort_values(by=['range'], ascending=False, axis=0)

In [ ]:
# See one -999999 in var3
train.var3.value_counts() #all
train.var3.value_counts()[:10] #first 10 levels

In [ ]:
# Dig into issues and redefine
train.loc[train.var3==-999999].shape

In [ ]:
# Replace -999999 with 0
train = train.replace(-999999,0)
train.loc[train.var3==-999999].shape

In [ ]:
# Create a new feature that points this unusual values
?

### Task. Your observations and data wrangling to discover issues
Please play with the data set. Use basic pandas codes and observe and explore issues. 

### Step 3: Exploratory Data Analysis (EDA) with Basic Functions

In [ ]:
train.describe()

In [ ]:
# Histogram of Each Feature
# This will generate bar charts/histogram for each. Later, after feature reductions, you can use it again.
class color:
   BOLD = '\033[1m'
   END = '\033[0m'
for i, col in enumerate(train.columns):
    sns.set()
    plt.figure(figsize=(5,3)) 
    plt.hist(train[col], bins=30)
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.title(col)
    plt.tight_layout()
    plt.show()

In [ ]:
# Calculate correlation matrix
df_corr = train.corr()
print(df_corr)

In [ ]:
# Task. Sort, get highest correlations (+-) using abs(), unstack(), sort_values(kind="quicksort") and Sprint

In [ ]:
# Lets pick some variables and get correlation
train[['var36', 'num_var5', 'var38', 'TARGET']].corr()

### Seaborn

In [ ]:
# Heatmap using seaborn
# You may want to run this after eliminating features
import seaborn as sns
sns.heatmap(train[['var36', 'num_var5', 'var38', 'TARGET']].corr(),annot=True)

In [ ]:
# Scatter plot with fitted line
sns.lmplot(x='var38', y='num_var5', data=train)
plt.show()

# Evaluate the plot. Discuss does this tell us anythings?

In [ ]:
sns.lmplot(x='var38', y='num_var5', hue='TARGET', data=train, fit_reg=True)
plt.show()

In [ ]:
# Boxplot
plt.figure(figsize=(16,9))
train_copy=train.drop(['var36','var38','num_var5', 'TARGET'],axis=1)
sns.boxplot(data=train['var38'])

plt.show()

# Discuss: On the same scale plot of fatures, it is not good idea. Need to do seperate or scale.
# Task: How to scale and how to seperately plot boxplots?
#group variables with features just in continuous

In [ ]:
sns.violinplot(data=train[['var38']])
plt.show()

In [ ]:
# MIN-MAX SCALING

min_max = MinMaxScaler()
min_max_scaled = min_max.fit_transform(train['var38'].values.reshape(-1, 1))
df_min_max = pd.DataFrame(min_max_scaled, columns=['Min_max_var38'])

print('MIN-MAX SCALING')
display(df_min_max.head())


In [ ]:
# Boxplot
plt.figure(figsize=(7,17))
sns.boxplot(data=df_min_max['Min_max_var38'])

plt.show()


In [ ]:
# Change figure size
plt.figure(figsize=(14,5))

sns.violinplot(x='TARGET', y='var38', data=train)

plt.show()

In [ ]:
# Distribution plot
sns.distplot(train['var36'], color='blue')

plt.show()

In [ ]:
# Count plot
sns.countplot(x='var36', data=train)

# Rotate labels
plt.xticks(rotation=90)

In [ ]:
# Joint plot: bivariate
# This take time
sns.jointplot(train.var38, train.num_var5, data=train, kind='kde', color='blue')

### Plotly

It is interactive effective tool for data visualization and EDA

In [ ]:
import plotly.express as px

In [ ]:
# Scatter plot
fig = px.scatter(train, x='var38', y='num_var5')

fig.show()


# This may not work right away. May need to install pack from pip or terminal. Jupyter-lab has issues with it.

In [ ]:
# Hovering features
fig = px.scatter(train, x='var38', y='num_var5', hover_data=['TARGET'])

fig.show()

In [ ]:
# Showing total along with hovering features
fig = px.scatter(train, x='var38', y='num_var5', hover_data=['TARGET'], size='var36', color='Grey')

fig.show()

In [ ]:
# Showing total along with hovering features
fig = px.box(train[['var36','var38']],  color='blue')

fig.show()

In [ ]:
# Task: get correlation matrix as corr_matrix, list it, label it by labels=list(corr_matrix), use px.imshow(corr_matrix,x=labels, y=labels) and fig.show()
# px.histogram(), px.density_heatmap()

In [ ]:
# Task: use of list(), range(), list(rage(train.shape[0])), .sort_values()

## Usefel codes

In [ ]:
# df is data set: Then

# if you want to get the rows where the color is green, then you’ll need to apply:
df.loc[df[‘Color’] == ‘Green’]

# Green and Rectangle
df.loc[(df[‘Color’] == ‘Green’) & (df[‘Shape’] == ‘Rectangle’)]

# Use of OR
df.loc[(df[‘Color’] == ‘Green’) | (df[‘Shape’] == ‘Rectangle’)]

#To get all the rows where the price is equal or greater than 10, you’ll need to apply this condition:
df.loc[df[‘Price’] >= 10]

#You can use the combination of symbols != to select the rows where the price is not equal to 15:
df.loc[df[‘Price’] != 15]


### Step 3b: Issues with This Type of Data

- Too many zeros. How to handle?

- How to detect associations among any two combination? (EDA with no Target) 

- Association with Target Variable (so feature selection can be employed)

- When to Use and Why Association?
    - To measure association (chi-sq, RR, OR, conditional proportion etc.) between two categorical variables

- When to Use and Why Correlation?
    - To measure between two numerical linear relationships
    

- When to not Use?

- Alternatives?


### Search: Why Mr. B write this? Make critiques

Notice how we can't even see the correlation matrix for all of the variables due to large number of columns. We will try the following methods:
    1. Melt the data that will result into decrease in number of columns but increase in number of rows. 
    2. Shrink the size of the columns to the most important 10 features by using Univariate feature selection technique.

### Step 3c: Feature Importance and Selection

This is just one application. Many methods and approach exist. The instructor will briefly go over the file, 'Feature Engineering, Data Reduction, and Curse.doc'

In general, the choice of evaluation metric heavily influences the algorithm, and it is these evaluation metrics which distinguish between the three main categories of feature selection algorithms: 

- wrappers, 
- filters and 
- embedded methods.

Filters are most common and cheap:



In [ ]:
# Let's scale the features first: Why?
from sklearn.preprocessing import MinMaxScaler
x = train.drop(['TARGET'], axis=1)
y = train['TARGET']
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)

In [ ]:
# Apply SelectKBest class to extract the 10 features that best explains the association relationships between Target and Univariate feature (chi-squa results are ranked) 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2 #see other options https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html
bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(x_scaled, y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x.columns)
featureScores = pd.concat([dfcolumns, dfscores], axis=1)
featureScores.columns = ['Feature', 'Score']
print(featureScores.nlargest(10, 'Score'))

In [ ]:
columns_10best_chi = ['num_meses_var5_ult3', 'ind_var5', 'ind_var30', 
           'var36', 'ind_var8_0', 'ind_var13', 
           'ind_var13_0', 'ind_var12_0', 
          'num_var5', 'ind_var13_corto', 'TARGET']

In [ ]:
# Now, we have 11+1 features from train set to proceed
sub_train = train[columns_10best_chi]

In [ ]:
# And take the same features from test set
sub_test = test[columns_10best_chi]

In [ ]:
print(sub_train.shape, sub_test.shape)

In [ ]:
sub_train.dtypes

## Feature Elimination Techniques

Univariate Feature Selection from Scikit

    2.1. GenericUnivarietSelect
    2.2. SelectKBest
    2.3. SelectPercentile
    2.4. SelectFpr
    2.5. SelectFdr
    2.6. SelectFwe
    2.7. chi2
    2.8. f_classif
    2.9. f_regerssion
    2.10. mutual_info_classif
    2.11. mutual_info_regression
    
Also usefel methods below. Plase play wtih these codes. May need fixing:

0) Removing Constant Features
1) Removing Quasi-constant: Quasi-constant features are those that show the same value for the great majority of the observations of the dataset.
2) Removing Feature From Low Variance

In [ ]:
# 0) Removing Constant Features
from sklearn.feature_selection import VarianceThreshold

# fit finds the features with zero variance
sel = VarianceThreshold(threshold=0)
sel.fit(train)
X1 = train.drop(columns=train.columns[~sel.get_support()])
X1t = test.drop(columns=test.columns[~sel.get_support()])

print(X1.shape)
print(X1t.shape)

#print(f'New sahape {X1.shape} number of feature removed {X_train.shape[1] - X1.shape[1]}')

In [ ]:
# 1) Removing Quasi-constant: Quasi-constant features are those that show the same value for the great majority of the observations of the dataset.

sel_quasi = VarianceThreshold(threshold=0.01)  # 0.1 indicates 99% of observations approximately
sel_quasi.fit(X1)
X2 = X1.drop(columns=X1.columns[~sel_quasi.get_support()])
X2t = X1t.drop(columns=X1t.columns[~sel_quasi.get_support()])

print(f'New sahape {X2.shape} number of feature removed {X1.shape[1] - X2.shape[1]}')

In [ ]:
# 2) Removing Feature From Low Variance
#VarianceThreshold is a simple baseline approach to feature selection. It removes all features whose variance doesn’t meet some threshold. By default, it removes all zero-variance features, i.e. features that have the same value in all samples.
#As an example, suppose that we have a dataset with boolean features, and we want to remove all features that are either one or zero (on or off) in more than 80% of the samples. Boolean features are Bernoulli random variables, and the variance of such variables is given by
#so we can select using the threshold .8 * (1 - .8):

from sklearn.feature_selection import VarianceThreshold

# First Example 
X = [[0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1]]
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel.fit_transform(X)

print(f'Variance value per columng {sel.variances_}, threshold {sel.threshold : 2.2f}')

sel = VarianceThreshold(threshold=0.01)
result = pd.DataFrame(sel.fit_transform(df_train))

sel.variances_

# Find the remaining column id
remain_features_id = np.where(sel.variances_ > sel.threshold)

# Assign remaining column name
result.columns = df_train.columns[remain_features_id]

result

## Discussion
Are all of these categorical variables? is it a problem when building predictive modeling?

## Need Powerful Tools and Packs

### Package 1: Pandas-Profiling

Import the pack or upoad it from https://github.com/pandas-profiling/pandas-profiling.

Shortly, this generates profile reports from a pandas DataFrame. The pandas df.describe() function is great but a little basic for serious exploratory data analysis. pandas_profiling extends the pandas DataFrame with df.profile_report() for quick data analysis.


In [ ]:
# Install here or using pip: >> pip install pandas-profiling
from pandas_profiling import ProfileReport

In [ ]:
# No need if not running
sub_train.profile_report(style={‘full_width’:True})

In [ ]:
profile = ProfileReport(sub_train, title="Pandas Profiling Report")
print(profile)

In [ ]:
profile.to_widgets()

In [ ]:
profile.to_file("your_report.html")

__NOTE__: Pandas-profiling may NOT process the data due to its size and not enough compute resource

### Package 2:  ClfAutoEDA

- Read the article https://medium.com/analytics-vidhya/automated-eda-for-classification-77c25b847e43
- Download the py code in the directory you are working: https://github.com/jatinkataria94/EDA-Classification/blob/master/ClfAutoEDA.py

In [ ]:
# import the autoEDA module
from ClfAutoEDA import *

In [ ]:
sub_train.shape

In [ ]:
#Just play with small data portion
#Setting parameter values
target_variable_name='TARGET'
labels=['Unhappy','Happy']
#Calling EDA function with parameters of choice
df_processed,num_features,cat_features=EDA(df=sub_train,labels=labels,
                                         target_variable_name=target_variable_name,
                                         data_summary_figsize=(6,6),
                                         corr_matrix_figsize=(6,6), 
                                         corr_matrix_annot=True,
                                         pairplt=True)

__NOTE__: Pandas-profiling couldn't process the data due to its size and not enough compute resource

## Pack 3. Sweetviz

Read the article https://towardsdatascience.com/powerful-eda-exploratory-data-analysis-in-just-two-lines-of-code-using-sweetviz-6c943d32f34

Install it using pip install sweetviz and run the next.

In [ ]:
import sweetviz

In [ ]:
#This will tke too much time if 
my_report = sweetviz.compare([sub_train, "Train"], [sub_test, "Test"], "TARGET")

In [ ]:
my_report.show_html("Report.html") # Not providing a filename will default to SWEETVIZ_REPORT.html

## Pack 4. Pycaret

A complex level pack that does all!

Read the article https://github.com/pycaret/pycaret and examples https://github.com/pycaret/pycaret/tree/master/examples.

Install it using pip install pycaret.

Practice it with the dataset here.

# More Resources to Practice
- https://www.kaggle.com/c/santander-customer-satisfaction and see many notebooks prepared
- https://www.kaggle.com/cast42/exploring-features ==> nice notebook to practice
